[package]
name = "grdf"
version = "0.4.1"
authors = ["Timothée Haudebourg <author@haudebourg.net>"]
edition = "2018"
categories = ["data-structures"]
keywords = ["grdf", "rdf", "semantic-web"]
description = "Generalized RDF graphs and datasets"
repository = "https://github.com/timothee-haudebourg/grdf"
documentation = "https://docs.rs/grdf"
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]
iref = "2.1.1"
rdf-types = "0.2.8"

[dev-dependencies]
static-iref = "1.0.0"