[package]
name = "grdf"
version = "0.8.0"
authors = ["Timothée Haudebourg <author@haudebourg.net>"]
edition = "2018"
categories = ["data-structures"]
keywords = ["grdf", "rdf", "semantic-web"]
description = "Generalized RDF graphs and datasets"
repository = "https://github.com/timothee-haudebourg/grdf"
documentation = "https://docs.rs/grdf"
license = "MIT/Apache-2.0"
readme = "README.md"

[features]
default = []
loc = [ "locspan", "rdf-types/loc" ]

[dependencies]
iref = "2.1.1"
rdf-types = "0.6.1"
derivative = "2.2.0"
locspan = { version = "0.5.2", optional = true }

[dev-dependencies]
static-iref = "1.0.0"